version: '3.8'
services:
  db:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    networks:
      - timebenchnw
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

networks:
  timebenchnw:

volumes:
  data:
