version: '3.8'
services:
  db:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    network_mode: host
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
